[custom]
;不要随意改变关键字，否则会导致出错
;自定义本地

;设置规则标志位
ruleset=DIRECT,https://raw.githubusercontent.com/Atomic994/subconverter/master/base/rules/Unbreak.list
ruleset=DIRECT,https://raw.githubusercontent.com/Atomic994/subconverter/master/base/rules/Direct.list
ruleset=🏠 回家,https://raw.githubusercontent.com/Atomic994/subconverter/master/base/rules/home.list
ruleset=✈ 机场屏蔽网站,https://raw.githubusercontent.com/Atomic994/subconverter/master/base/rules/JCPBWZ.list
ruleset=🤖 AI服务,https://raw.githubusercontent.com/Atomic994/subconverter/master/base/rules/AI.list
ruleset=🎞 Emby公益服,https://raw.githubusercontent.com/Atomic994/subconverter/master/base/rules/Emby.list
ruleset=📲 Telegram,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Telegram/Telegram.list
ruleset=📲 Whatsapp,https://raw.githubusercontent.com/Atomic994/subconverter/master/base/rules/Whatsapp.list
ruleset=🔒 Web3,https://raw.githubusercontent.com/Atomic994/subconverter/master/base/rules/Web3.list
ruleset=𝕏 Twitter,https://raw.githubusercontent.com/Atomic994/subconverter/master/base/rules/Twitter.list
ruleset=🎶 TikTok,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/TikTok/TikTok.list
ruleset=🎥 Youtube,https://raw.githubusercontent.com/Atomic994/subconverter/master/base/rules/ACL4SSR/Clash/Ruleset/YouTube.list
ruleset=🎬 Netflix,https://raw.githubusercontent.com/Atomic994/subconverter/master/base/rules/ACL4SSR/Clash/Ruleset/Netflix.list
ruleset=🎬 Disney+,https://raw.githubusercontent.com/Atomic994/subconverter/master/base/rules/ACL4SSR/Clash/Ruleset/DisneyPlus.list
ruleset=🍎 Apple,https://raw.githubusercontent.com/Atomic994/subconverter/master/base/rules/ACL4SSR/Clash/Ruleset/Apple.list
ruleset=🎮 Game,https://raw.githubusercontent.com/Atomic994/subconverter/master/base/rules/Game.list
ruleset=🎌 日本媒体,https://raw.githubusercontent.com/Atomic994/subconverter/master/base/rules/Japanmedia.list
ruleset=🎤 韩国媒体,https://raw.githubusercontent.com/Atomic994/subconverter/master/base/rules/Koreamedia.list
ruleset=🗼 台湾媒体,https://raw.githubusercontent.com/Atomic994/subconverter/master/base/rules/Taiwanmedia.list
ruleset=🏙 香港媒体,https://raw.githubusercontent.com/Atomic994/subconverter/master/base/rules/Hongkongmedia.list
ruleset=🦁 狮城媒体,https://raw.githubusercontent.com/Atomic994/subconverter/master/base/rules/Singaporemedia.list
ruleset=🗽 欧美媒体,https://raw.githubusercontent.com/Atomic994/subconverter/master/base/rules/Oumeimeiti.list
ruleset=🎯 Proxy,https://raw.githubusercontent.com/Atomic994/subconverter/master/base/rules/Proxy.list
ruleset=🇨🇳 中国连接,https://raw.githubusercontent.com/Atomic994/subconverter/master/base/rules/ACL4SSR/Clash/ChinaDirectIP.list
;ruleset=🇨🇳 中国连接,[]GEOIP,CN
ruleset=🚀 全球连接,[]FINAL
;设置规则标志位

;设置分组标志位
custom_proxy_group=🎯 Proxy`select`[]💿 自动选择`[]🇭🇰 香港节点`[]🇹🇼 台湾节点`[]🇯🇵 日本节点`[]🇰🇷 韩国节点`[]🇺🇸 美国节点`[]🇸🇬 狮城节点`[]🌍 其它地区`[]♻️ 手动切换1`[]♻️ 手动切换2`[]♻️ 手动切换3
custom_proxy_group=💿 自动选择`url-test`.*`http://www.gstatic.com/generate_204`300,,100
custom_proxy_group=🇭🇰 香港节点`select`(港|HK|Hong Kong)
custom_proxy_group=🇹🇼 台湾节点`select`(台|新北|彰化|TW|Taiwan)
custom_proxy_group=🇯🇵 日本节点`select`(日本|川日|东京|大阪|泉日|埼玉|沪日|深日|[^-]日|JP|Japan)
custom_proxy_group=🇰🇷 韩国节点`select`(KR|Korea|KOR|首尔|韩|韓)
custom_proxy_group=🇺🇸 美国节点`select`(美国|波特兰|达拉斯|俄勒冈|凤凰城|费利蒙|硅谷|拉斯维加斯|洛杉矶|圣何塞|圣克拉拉|西雅图|芝加哥|US|United States)
custom_proxy_group=🇸🇬 狮城节点`select`(新加坡|坡|狮城|SG|Singapore)
custom_proxy_group=🌍 其它地区`select`(俄|印|德|英|荷|法|意|西|以|泰|迪|约|巴|智|土|阿|拿|菲|澳|爱尔兰|回国|回|埃|马|越|尼|United Kingdom|Germany|Netherlands|Australia|Italy|Spain|Brazil|Chile|India|Israel|Thailand|Philippines|Dubai|Vietnam|Malaysia|Johannesburg)
custom_proxy_group=♻️ 手动切换1`select`.*
custom_proxy_group=♻️ 手动切换2`select`.*
custom_proxy_group=♻️ 手动切换3`select`.*
custom_proxy_group=🏠 回家`select`[]DIRECT`[]🎯 Proxy`(中国|中山|CN|China)
custom_proxy_group=✈ 机场屏蔽网站`select`[]🎯 Proxy`[]DIRECT`[]💿 自动选择`[]🇭🇰 香港节点`[]🇹🇼 台湾节点`[]🇯🇵 日本节点`[]🇰🇷 韩国节点`[]🇺🇸 美国节点`[]🇸🇬 狮城节点`[]🌍 其它地区`[]♻️ 手动切换1`[]♻️ 手动切换2`[]♻️ 手动切换3
custom_proxy_group=🤖 AI服务`select`[]🎯 Proxy`[]DIRECT`[]💿 自动选择`[]🇭🇰 香港节点`[]🇹🇼 台湾节点`[]🇯🇵 日本节点`[]🇰🇷 韩国节点`[]🇺🇸 美国节点`[]🇸🇬 狮城节点`[]🌍 其它地区`[]♻️ 手动切换1`[]♻️ 手动切换2`[]♻️ 手动切换3
custom_proxy_group=🎞 Emby公益服`select`[]🎯 Proxy`[]DIRECT`[]💿 自动选择`[]🇭🇰 香港节点`[]🇹🇼 台湾节点`[]🇯🇵 日本节点`[]🇰🇷 韩国节点`[]🇺🇸 美国节点`[]🇸🇬 狮城节点`[]🌍 其它地区`[]♻️ 手动切换1`[]♻️ 手动切换2`[]♻️ 手动切换3
custom_proxy_group=📲 Telegram`select`[]🎯 Proxy`[]DIRECT`[]💿 自动选择`[]🇭🇰 香港节点`[]🇹🇼 台湾节点`[]🇯🇵 日本节点`[]🇰🇷 韩国节点`[]🇺🇸 美国节点`[]🇸🇬 狮城节点`[]🌍 其它地区`[]♻️ 手动切换1`[]♻️ 手动切换2`[]♻️ 手动切换3
custom_proxy_group=📲 Whatsapp`select`[]🎯 Proxy`[]DIRECT`[]💿 自动选择`[]🇭🇰 香港节点`[]🇹🇼 台湾节点`[]🇯🇵 日本节点`[]🇰🇷 韩国节点`[]🇺🇸 美国节点`[]🇸🇬 狮城节点`[]🌍 其它地区`[]♻️ 手动切换1`[]♻️ 手动切换2`[]♻️ 手动切换3
custom_proxy_group=🔒 Web3`select`[]🎯 Proxy`[]DIRECT`[]💿 自动选择`[]🇭🇰 香港节点`[]🇹🇼 台湾节点`[]🇯🇵 日本节点`[]🇰🇷 韩国节点`[]🇺🇸 美国节点`[]🇸🇬 狮城节点`[]🌍 其它地区`[]♻️ 手动切换1`[]♻️ 手动切换2`[]♻️ 手动切换3
custom_proxy_group=𝕏 Twitter`select`[]🎯 Proxy`[]DIRECT`[]💿 自动选择`[]🇭🇰 香港节点`[]🇹🇼 台湾节点`[]🇯🇵 日本节点`[]🇰🇷 韩国节点`[]🇺🇸 美国节点`[]🇸🇬 狮城节点`[]🌍 其它地区`[]♻️ 手动切换1`[]♻️ 手动切换2`[]♻️ 手动切换3
custom_proxy_group=🎶 TikTok`select`[]🎯 Proxy`[]DIRECT`[]💿 自动选择`[]🇭🇰 香港节点`[]🇹🇼 台湾节点`[]🇯🇵 日本节点`[]🇰🇷 韩国节点`[]🇺🇸 美国节点`[]🇸🇬 狮城节点`[]🌍 其它地区`[]♻️ 手动切换1`[]♻️ 手动切换2`[]♻️ 手动切换3
custom_proxy_group=🎥 Youtube`select`[]🎯 Proxy`[]DIRECT`[]💿 自动选择`[]🇭🇰 香港节点`[]🇹🇼 台湾节点`[]🇯🇵 日本节点`[]🇰🇷 韩国节点`[]🇺🇸 美国节点`[]🇸🇬 狮城节点`[]🌍 其它地区`[]♻️ 手动切换1`[]♻️ 手动切换2`[]♻️ 手动切换3
custom_proxy_group=🎬 Netflix`select`[]🎯 Proxy`[]DIRECT`[]💿 自动选择`[]🇭🇰 香港节点`[]🇹🇼 台湾节点`[]🇯🇵 日本节点`[]🇰🇷 韩国节点`[]🇺🇸 美国节点`[]🇸🇬 狮城节点`[]🌍 其它地区`[]♻️ 手动切换1`[]♻️ 手动切换2`[]♻️ 手动切换3
custom_proxy_group=🎬 Disney+`select`[]🎯 Proxy`[]DIRECT`[]💿 自动选择`[]🇭🇰 香港节点`[]🇹🇼 台湾节点`[]🇯🇵 日本节点`[]🇰🇷 韩国节点`[]🇺🇸 美国节点`[]🇸🇬 狮城节点`[]🌍 其它地区`[]♻️ 手动切换1`[]♻️ 手动切换2`[]♻️ 手动切换3
custom_proxy_group=🍎 Apple`select`[]🎯 Proxy`[]DIRECT`[]💿 自动选择`[]🇭🇰 香港节点`[]🇹🇼 台湾节点`[]🇯🇵 日本节点`[]🇰🇷 韩国节点`[]🇺🇸 美国节点`[]🇸🇬 狮城节点`[]🌍 其它地区`[]♻️ 手动切换1`[]♻️ 手动切换2`[]♻️ 手动切换3
custom_proxy_group=🎮 Game`select`[]🎯 Proxy`[]DIRECT`[]💿 自动选择`[]🇭🇰 香港节点`[]🇹🇼 台湾节点`[]🇯🇵 日本节点`[]🇰🇷 韩国节点`[]🇺🇸 美国节点`[]🇸🇬 狮城节点`[]🌍 其它地区`[]♻️ 手动切换1`[]♻️ 手动切换2`[]♻️ 手动切换3
custom_proxy_group=🎌 日本媒体`select`[]🎯 Proxy`[]DIRECT`[]💿 自动选择`[]🇭🇰 香港节点`[]🇹🇼 台湾节点`[]🇯🇵 日本节点`[]🇰🇷 韩国节点`[]🇺🇸 美国节点`[]🇸🇬 狮城节点`[]🌍 其它地区`[]♻️ 手动切换1`[]♻️ 手动切换2`[]♻️ 手动切换3
custom_proxy_group=🎤 韩国媒体`select`[]🎯 Proxy`[]DIRECT`[]💿 自动选择`[]🇭🇰 香港节点`[]🇹🇼 台湾节点`[]🇯🇵 日本节点`[]🇰🇷 韩国节点`[]🇺🇸 美国节点`[]🇸🇬 狮城节点`[]🌍 其它地区`[]♻️ 手动切换1`[]♻️ 手动切换2`[]♻️ 手动切换3
custom_proxy_group=🗼 台湾媒体`select`[]🎯 Proxy`[]DIRECT`[]💿 自动选择`[]🇭🇰 香港节点`[]🇹🇼 台湾节点`[]🇯🇵 日本节点`[]🇰🇷 韩国节点`[]🇺🇸 美国节点`[]🇸🇬 狮城节点`[]🌍 其它地区`[]♻️ 手动切换1`[]♻️ 手动切换2`[]♻️ 手动切换3
custom_proxy_group=🏙 香港媒体`select`[]🎯 Proxy`[]DIRECT`[]💿 自动选择`[]🇭🇰 香港节点`[]🇹🇼 台湾节点`[]🇯🇵 日本节点`[]🇰🇷 韩国节点`[]🇺🇸 美国节点`[]🇸🇬 狮城节点`[]🌍 其它地区`[]♻️ 手动切换1`[]♻️ 手动切换2`[]♻️ 手动切换3
custom_proxy_group=🦁 狮城媒体`select`[]🎯 Proxy`[]DIRECT`[]💿 自动选择`[]🇭🇰 香港节点`[]🇹🇼 台湾节点`[]🇯🇵 日本节点`[]🇰🇷 韩国节点`[]🇺🇸 美国节点`[]🇸🇬 狮城节点`[]🌍 其它地区`[]♻️ 手动切换1`[]♻️ 手动切换2`[]♻️ 手动切换3
custom_proxy_group=🗽 欧美媒体`select`[]🎯 Proxy`[]DIRECT`[]💿 自动选择`[]🇭🇰 香港节点`[]🇹🇼 台湾节点`[]🇯🇵 日本节点`[]🇰🇷 韩国节点`[]🇺🇸 美国节点`[]🇸🇬 狮城节点`[]🌍 其它地区`[]♻️ 手动切换1`[]♻️ 手动切换2`[]♻️ 手动切换3
custom_proxy_group=🇨🇳 中国连接`select`[]DIRECT`[]🎯 Proxy`[]💿 自动选择`[]🇭🇰 香港节点`[]🇹🇼 台湾节点`[]🇯🇵 日本节点`[]🇰🇷 韩国节点`[]🇺🇸 美国节点`[]🇸🇬 狮城节点`[]🌍 其它地区`[]♻️ 手动切换1`[]♻️ 手动切换2`[]♻️ 手动切换3
custom_proxy_group=🚀 全球连接`select`[]🎯 Proxy`[]DIRECT
;设置分组标志位

enable_rule_generator=true
overwrite_original_rules=true
